services:
  client:
    build: .
    container_name: mcp-go-cli
    stdin_open: true
    tty: true
    volumes:
      - .:/app
      # bind your resource here
      - /Users/phudit.t/projects:/projects
    env_file:
      - .env
    command: /app/mcp-cli
    depends_on:
      - ollama

  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - 11434:11434
